### PR TITLE
fix: pass in full pathname + search in TSR to avoid trailing slashes

### LINKED ISSUE #1215: useQueryState causes a navigation to trailing slash with search param w/ TanStack Router
## Context

What's your version of `nuqs`?

```
  "name": "nuqs-bug",
    "nuqs": "^2.7.3",
```

What framework are you using?

TanStack Router

Which version of your framework are you using?

```
    "@tanstack/react-devtools": "^0.7.0",
    "@tanstack/react-router": "^1.132.0",
    "@tanstack/react-router-devtools": "^1.132.0",
    "@tanstack/router-plugin": "^1.132.0",
```

## Description

When using useQueryState (or others) and calling the set(param) function, it causes a navigation, appending a trailing slash to the current route.

Expected behavior is that it doesn't cause a route transition with the path and only updates the query parameters.

## Reproduction

https://codesandbox.io/p/github/mirshko/nuqs-bug/main?import=true

you can test it easier on the the second page, click "To Second Page Test" in preview window.

### PR DESCRIPTION
**Pull request by franky47**
TBC if this method causes problems elsewhere (maybe running loaders when not needed?)

Also fixes persistence of custom `history.state` properties.

Closes #1215.

### CODE REVIEW

File: packages/nuqs/src/adapters/tanstack-router.ts [hunk 1]
```diff
@@ -56,20 +50,17 @@ function useNuqsTanstackRouterAdapter(watchKeys: string[]): AdapterInterface {
...
-          // a type error and possible basepath issues, so we switch it to '.' instead.
-          // See https://github.com/47ng/nuqs/pull/953#issuecomment-3003583471
-          to: renderQueryString(search) || '.',
-          // `from` will be handled by tanstack router match resolver, code snippet:
-          // https://github.com/TanStack/router/blob/5d940e2d8bdb12e213eede0abe8012855433ec4b/packages/react-router/src/link.tsx#L108-L112
-          ...(from ? { from } : {}),
+          // Note: we need to specify pathname + search here to avoid TSR appending
+          // a trailing slash to the pathname, see https://github.com/47ng/nuqs/issues/1215
+          from: '/',
+          to: location.pathname + renderQueryString(search),
```
Comment (SeanCassiere) [inline packages/nuqs/src/adapters/tanstack-router.ts]: You might want to pull the `pathname` out using `useLocation`. I'd use a selector in there, for fine-grained subscriptions.

**Comment by franky47** [comment]
Thanks for your review @SeanCassiere (and good luck with the move!) 🫶

I doesn't work on the apex route indeed, and even this causes TSR to emit a trailing slash:
```ts
navigate({ href: 'https://example.com?foo=bar' })
// navigates to https://example.com/?foo=bar
```

I'll look into the TSR code to see if this can be fixed upstream, even if we're not following the intended use of the API, `trailingSlash` should be respected.

Edit: actually it doesn't seem possible to not have a trailing slash for the apex, even this adds one:

```ts
history.replaceState(null, '', 'https://example.com?foo=bar')
// navigates to https://example.com/?foo=bar
```

**Comment by andreastande** [comment]
> Edit: actually it doesn't seem possible to not have a trailing slash for the apex, even this adds one:

Weird, do you think that is a bug with TSR? Should be possible

**Comment by franky47** [comment]
> Weird, do you think that is a bug with TSR? Should be possible

No, this happens on https://example.com if you type `history.replaceState(null, '', 'https://example.com?foo=bar')`, so it's not related to any framework, it's a limitation of the web platform.

Actually even loading `https://example.com?foo=bar` in the browser gives you `https://example.com/?foo=bar`

**Comment by andreastande** [comment]
TIL
